version: '3.0'

services:
  grafana:
    container_name: 'grafana-github-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/:rw
      - ./provisioning:/etc/grafana/provisioning
      - ./grafana-logs:/var/log/grafana
    environment:
      - GF_LOG_MODE=console,file
      - GF_LOG_LEVEL=debug
